package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/argon2"
)

// Argon2Params are the cost parameters of a password hash.
//
// They are stored inside the encoded hash rather than only in this file, so
// that raising them later does not invalidate existing hashes: an old hash is
// verified with the parameters it was made with, and re-hashed on the next
// successful login if the operator wants to move forward.
type Argon2Params struct {
	// Memory is the working set in KiB.
	Memory uint32
	// Time is the number of passes.
	Time uint32
	// Parallelism is the number of lanes.
	Parallelism uint8
	// SaltLength and KeyLength are in bytes.
	SaltLength uint32
	KeyLength  uint32
}

// DefaultArgon2Params is a deliberately expensive setting.
//
// A password is the one credential in this system that a human chose, which
// makes it the one worth brute-forcing offline. The cost is paid once per
// login, by one person, and is invisible next to the time it takes to type the
// password.
func DefaultArgon2Params() Argon2Params {
	return Argon2Params{
		Memory:      64 * 1024, // 64 MiB
		Time:        3,
		Parallelism: 1,
		SaltLength:  16,
		KeyLength:   32,
	}
}

// ErrInvalidPasswordHash is returned for a hash that cannot be parsed.
var ErrInvalidPasswordHash = errors.New("auth: not a valid argon2id password hash")

// HashPassword derives a hash from a password using the default parameters.
func HashPassword(password string) (string, error) {
	return HashPasswordWith(password, DefaultArgon2Params())
}

// HashPasswordWith derives a hash using explicit parameters.
//
// Tests use this to run with parameters small enough to be fast. Production
// never should: the whole point of the cost is that it is expensive.
func HashPasswordWith(password string, p Argon2Params) (string, error) {
	if password == "" {
		return "", errors.New("auth: password must not be empty")
	}
	if p.Memory == 0 || p.Time == 0 || p.Parallelism == 0 || p.SaltLength == 0 || p.KeyLength == 0 {
		return "", errors.New("auth: argon2 parameters must all be non-zero")
	}

	salt := make([]byte, p.SaltLength)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("auth: salt: %w", err)
	}

	key := argon2.IDKey([]byte(password), salt, p.Time, p.Memory, p.Parallelism, p.KeyLength)

	// The standard encoded form, the one every argon2 implementation reads.
	// Storing it this way rather than as a struct means the hash can be moved
	// between systems — and generated by `openssl` or a Python one-liner — with
	// nothing to explain.
	return fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s",
		argon2.Version, p.Memory, p.Time, p.Parallelism,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key),
	), nil
}

// PasswordHash is a parsed argon2id hash.
type PasswordHash struct {
	params Argon2Params
	salt   []byte
	key    []byte
}

// ParsePasswordHash reads the encoded form.
func ParsePasswordHash(encoded string) (PasswordHash, error) {
	var h PasswordHash

	parts := strings.Split(strings.TrimSpace(encoded), "$")
	// Leading empty string from the leading "$", then the algorithm, version
	// and parameters, then the salt and the key.
	if len(parts) != 6 || parts[0] != "" {
		return h, ErrInvalidPasswordHash
	}
	if parts[1] != "argon2id" {
		return h, fmt.Errorf("auth: hash uses %q, want argon2id", parts[1])
	}

	var version int
	if _, err := fmt.Sscanf(parts[2], "v=%d", &version); err != nil {
		return h, ErrInvalidPasswordHash
	}
	if version != argon2.Version {
		return h, fmt.Errorf("auth: hash version %d is not supported (want %d)", version, argon2.Version)
	}

	var p Argon2Params
	if _, err := fmt.Sscanf(parts[3], "m=%d,t=%d,p=%d", &p.Memory, &p.Time, &p.Parallelism); err != nil {
		return h, ErrInvalidPasswordHash
	}
	// A hash that claims a gigabyte of memory is a denial of service aimed at
	// the login endpoint. The limit is far above any sane setting and far below
	// anything that would hurt the host.
	if p.Memory == 0 || p.Memory > 1<<20 {
		return h, fmt.Errorf("auth: hash declares %d KiB of memory, which is out of range", p.Memory)
	}
	if p.Time == 0 || p.Time > 100 {
		return h, fmt.Errorf("auth: hash declares %d passes, which is out of range", p.Time)
	}
	if p.Parallelism == 0 || p.Parallelism > 16 {
		return h, fmt.Errorf("auth: hash declares %d lanes, which is out of range", p.Parallelism)
	}

	salt, err := base64.RawStdEncoding.DecodeString(parts[4])
	if err != nil {
		return h, ErrInvalidPasswordHash
	}
	key, err := base64.RawStdEncoding.DecodeString(parts[5])
	if err != nil {
		return h, ErrInvalidPasswordHash
	}
	if len(salt) == 0 || len(key) == 0 {
		return h, ErrInvalidPasswordHash
	}

	h.params = p
	h.params.SaltLength = uint32(len(salt))
	h.params.KeyLength = uint32(len(key))
	h.salt = salt
	h.key = key
	return h, nil
}

// Verify reports whether a password matches, in constant time.
//
// The comparison is subtle.ConstantTimeCompare rather than bytes.Equal: the
// derived key is secret, and a comparison that returns early on the first
// differing byte turns "guess the password" into "guess the password one byte
// at a time".
func (h PasswordHash) Verify(password string) bool {
	if len(h.key) == 0 {
		return false
	}
	key := argon2.IDKey([]byte(password), h.salt, h.params.Time, h.params.Memory,
		h.params.Parallelism, h.params.KeyLength)
	return subtle.ConstantTimeCompare(key, h.key) == 1
}

// NeedsRehash reports whether a hash was made with weaker parameters than the
// given ones.
func (h PasswordHash) NeedsRehash(want Argon2Params) bool {
	return h.params.Memory < want.Memory ||
		h.params.Time < want.Time ||
		h.params.Parallelism < want.Parallelism ||
		h.params.KeyLength < want.KeyLength
}
